# Generated by Django 5.2.8 on 2025-11-09 02:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "available_cash",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=15
                    ),
                ),
                (
                    "initial_cash",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                (
                    "shares",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "avg_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("secure", "Secure"),
                            ("moderate", "Moderate"),
                            ("aggressive", "Aggressive"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="trading.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "holdings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "ticker"],
                        name="holdings_portfol_527079_idx",
                    ),
                    models.Index(fields=["ticker"], name="holdings_ticker_08d63f_idx"),
                ],
                "unique_together": {("portfolio", "ticker", "strategy")},
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("shares", models.DecimalField(decimal_places=4, max_digits=15)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("secure", "Secure"),
                            ("moderate", "Moderate"),
                            ("aggressive", "Aggressive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="trading.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "trades",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["portfolio", "ticker"], name="trades_portfol_30422d_idx"
                    ),
                    models.Index(
                        fields=["portfolio", "timestamp"],
                        name="trades_portfol_f5ccff_idx",
                    ),
                    models.Index(
                        fields=["ticker", "timestamp"], name="trades_ticker_dda1f9_idx"
                    ),
                ],
            },
        ),
    ]
